name: Docker Deploy Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Image
        run: |
          docker build -t ghcr.io/jhsassociatesllp/jhs-ope:production .
          docker push ghcr.io/jhsassociatesllp/jhs-ope:production

      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 2232
          script: |
            docker stop jhs-ope-production || true
            docker rm jhs-ope-production || true

            docker pull ghcr.io/jhsassociatesllp/jhs-ope:production

            docker run -d \
            --name jhs-ope-production \
            --env-file /www/wwwroot/secrets/ope_production.env \
            -p 9010:8000 \
            --restart always \
            ghcr.io/jhsassociatesllp/jhs-ope:production

            docker image prune -f
