name: Docker Deploy Staging

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Image
        run: |
          docker build -t ghcr.io/jhsassociatesllp/jhs-ope:staging .
          docker push ghcr.io/jhsassociatesllp/jhs-ope:staging

      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 2232
          script: |
            docker stop jhs-ope-staging || true
            docker rm jhs-ope-staging || true

            docker pull ghcr.io/jhsassociatesllp/jhs-ope:staging

            docker run -d \
            --name jhs-ope-staging \
            --env-file /www/wwwroot/secrets/ope_staging.env \
            -p 9009:8000 \
            --restart always \
            ghcr.io/jhsassociatesllp/jhs-ope:staging

            docker image prune -f

